
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_project'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

vars:
  outbreak_threshold_multiplier: 3.0
  rolling_days: 7